

export const MainLayout = () => {
  return (
    <div className={styles.content}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home Page</h1>
      
      <Navbar/>

      <main className={styles.main}>
       <h1 className={styles.title}>
        Ir a 
        <Link href="/about">
          About
        </Link>

       </h1>
       <p className={styles.description}>
        Editing by <code className={styles.code}>Ir</code>pages/index.tsx
       </p>
      </main>
    </div>
  )
}
